---
kind: pipeline
name: default

steps:
  - name: build
    image: linuxserver/docker-compose
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker-compose build
  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
    when:
      status:
        - success
        - failure
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock