version: "3.9"

services:
  mandelbrot:
    image: 32874687/mandelbrot
    build: mandelbrot/
    expose:
      - "80"
  server:
    image: 32874687/mandelbrot-server
    build: server/
    depends_on:
      - mandelbrot
    ports:
      - "8080:80"
